steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/familyguy-app', '.']

# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/familyguy-app']

# Deploy container image to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - "apply"
  - "-f"
  - "gke.yaml"
  env:
  - "CLOUDSDK_COMPUTE_REGION=us-central1-c"
  - "CLOUDSDK_CONTAINER_CLUSTER=cluster-1"

# Update the deployment with the new image
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - "set"
  - "image"
  - "deployment/familyguy-app"
  - "familyguy-app=gcr.io/$PROJECT_ID/familyguy-app:latest"
  env:
  - "CLOUDSDK_COMPUTE_REGION=us-central1-c"
  - "CLOUDSDK_CONTAINER_CLUSTER=cluster-1"

images:
- 'gcr.io/$PROJECT_ID/familyguy-app'

options:
  logging: CLOUD_LOGGING_ONLY
