apiVersion: apps/v1
kind: Deployment
metadata:
  name: familyguy-app  # ✅ Changed from "gcp-devops-gke" to "familyguy-app"
  namespace: familygyu-app-ns  # ✅ Added namespace to match the Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: familyguy  # ✅ Updated label to match selector
  template:
    metadata:
      labels:
        app: familyguy  # ✅ Updated label to match selector
    spec:
      containers:
      - name: familyguy-app
        image: gcr.io/rosy-decker-447215-e6/familyguy-app:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: familyguy-app-service
  namespace: familygyu-app-ns
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: familyguy  # ✅ Updated to match the Deployment selector
  type: LoadBalancer
